apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: monitoring
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 31001
  type: NodePort